## Section 4.2

In [4]:
# Import the array package
from numpy import array 

# Create the array 
l = [1.0, 2.0, 3.0]
a = array(l)

# Display the array 
print(a)

# Display the array shape 
print(a.shape)

# Display the array data type
print(a.dtype)

[1. 2. 3.]
(3,)
float64


## Section 4.3

In [8]:
# Import the empty package 
from numpy import empty 

# Create the empty array
a = empty([3,3])

# Display the empty array 
print(a)

[[0.00000000e+000 1.29073862e-231 6.93342483e-310]
 [3.95252517e-323 1.97626258e-323 2.22835000e-314]
 [2.22835001e-314 2.22789389e-314 2.22789396e-314]]


In [9]:
# Import the zeros package 
from numpy import zeros 

# Create the array of zeros 
a = zeros([3, 5])

# Display the array of zeros 
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [10]:
# Import the ones package 
from numpy import ones 

# Create the array of ones 
a = ones([5])

# Display the array of ones 
print(a)

[1. 1. 1. 1. 1.]


## Section 4.4

In [12]:
# Import the packages needed 
from numpy import array, vstack 

# Create the arrays
a1 = array([1, 2, 3])
a2 = array([4, 5, 6])

# Stack the arrays vertically 
a3 = vstack((a1, a2))

# Display the new stacked array and its shape 
print(a3)
print(a3.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [13]:
# Import the packages needed 
from numpy import array, hstack 

# Create the arrays
a1 = array([1, 2, 3])
a2 = array([4, 5, 6])

# Stack the arrays horizontally
a3 = hstack((a1, a2))

# Display the new stacked array and its shape 
print(a3)
print(a3.shape)

[1 2 3 4 5 6]
(6,)


## Extension 

#### Locate and develop an example for 3 additional NumPy functions for creating arrays.

In [14]:
# Import the eye package 
from numpy import eye

# Create the array of ones on the diagonal and zeros elsewhere
a = eye(5)

# Display the eye array 
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [15]:
# Import the identity package 
from numpy import eye

# Create the identity array 
a = eye(5)

# Display the eye array 
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


What's the difference between 'eye' and 'indentity'? Not much. Identity actually calls eye (see below).  However, eye can be control the length with variable M, and can be offset with variable k.

In [16]:
def identity(n, dtype=None):
    from numpy import eye
    return eye(n, dtype=dtype)

In [21]:
# Import the eye package 
from numpy import eye

# Create the array of ones on the diagonal and zeros elsewhere
a = eye(5, M = 4, k = 1)

# Display the eye array 
print(a)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [23]:
# Import the ones_like package 
from numpy import ones_like

# Create the array to base the ones array on
a1 = array([1, 2, 3, 4, 5])

# Create the ones array
a2 = ones_like(a1)

# Display the eye array 
print(a2)

[1 1 1 1 1]


In [25]:
# Import the full package 
from numpy import full

# Create the full array
a = full([3, 5], 5)

# Display the eye array 
print(a)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


Locate and develop an example for 3 additional NumPy functions for combining arrays.

In [26]:
# Import the packages needed 
from numpy import array, concatenate 

# Create the arrays
a1 = array([1, 2, 3])
a2 = array([4, 5, 6])

# Concatenate 
a3 = concatenate((a1, a2))

# Display the new stacked array and its shape 
print(a3)
print(a3.shape)

[1 2 3 4 5 6]
(6,)


As can be seen, concatenate produces the same result as hstack.  Hstack actually uses the concatenate function (see below).